### ISSUE TITLE
Error running p2p_scanner.py

### ISSUE THREAD

**Issue by nachobonilla** [6e726d/WIG#2]
Hi Andres !

Been really interested on the subject lately and found that you seem the only one to have tackled the information gathering of wi-fi direct. After trying some time using the p2p_scanner.py, I haven´t been able to get pass through the following error:
 
python2.7 p2p_scanner.py wlan0mon
Process Transmitter-1:
Traceback(most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self_run()
  File "p2p_scanner.py", line 152, in run
    self.pd.sendpacket(frame)
  AtributeError: sendpacket

I would really appreciate if you have any ideas on what the problem might be.

**Comment by 6e726d** [comment]
Apparently you are using an old version of pcapy library that is missing the sendpacket method. My recomendation is to create a virtualenv and build the new version of pcapy.

**Comment by nachobonilla** [comment]
Thank you very much for the help, issue solved !
